apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  volumes:
  - name: task-pv-storage
    persistentVolumeClaim:
        claimName: task-pv-claim
  containers:
  - name: nginx-server
    image: docker.io/nginx:latest
    ports:
    - containerPort: 80
      hostPort: 8080
    envFrom:
    - configMapRef:
        name: env
        optional: false
    volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: task-pv-storage
